const List<Map<String, dynamic>> candidateList = [
  {
    "name": "SHRISTI",
    "logo": "01-01.jpg",
    "forSPL": true,
    "isMale": false,
    "hover": false,
    "click": false,
    "count": 0,
  },
  {
    "name": "RISHAB",
    "logo": "02-01.jpg",
    "forSPL": true,
    "isMale": true,
    "hover": false,
    "click": false,
    "count": 0,
  },
  {
    "name": "ADIYANT",
    "logo": "03-01.jpg",
    "forSPL": true,
    "isMale": true,
    "hover": false,
    "click": false,
    "count": 0,
  },
  {
    "name": "SNEHA",
    "logo": "04-01.jpg",
    "forSPL": true,
    "isMale": false,
    "hover": false,
    "click": false,
    "count": 0,
  },
  {
    "name": "KSHIRABDHI",
    "logo": "05-01.jpg",
    "forSPL": true,
    "isMale": false,
    "hover": false,
    "click": false,
    "count": 0,
  },
  // {
  //   "name": "ARUNDHATI",
  //   "logo": "06-01.jpg",
  //   "forSPL": true,
  //   "isMale": false,
  //   "hover": false,
  //   "click": false,
  //   "count": 0,
  // },
  {
    "name": "PURVI",
    "logo": "07-01.jpg",
    "forSPL": false,
    "isMale": false,
    "hover": false,
    "click": false,
    "count": 0,
  },
  {
    "name": "SUBHAM",
    "logo": "08-01.jpg",
    "forSPL": false,
    "isMale": true,
    "hover": false,
    "click": false,
    "count": 0,
  },
  {
    "name": "SHAGUN",
    "logo": "09-01.jpg",
    "forSPL": false,
    "isMale": false,
    "hover": false,
    "click": false,
    "count": 0,
  },
  {
    "name": "VAIBHAV",
    "logo": "10-01.jpg",
    "forSPL": false,
    "isMale": true,
    "hover": false,
    "click": false,
    "count": 0,
  },
  // {
  //   "name": "ARAV",
  //   "logo": "11-01.jpg",
  //   "forSPL": false,
  //   "isMale": true,
  //   "hover": false,
  //   "click": false,
  //   "count": 0,
  // },
];
